-- Insert default permissions
INSERT INTO permissions (id, name, description, resource_type) VALUES
    (gen_random_uuid(), 'item:create', 'Create new inventory items', 'item'),
    (gen_random_uuid(), 'item:read', 'View inventory items', 'item'),
    (gen_random_uuid(), 'item:update', 'Update inventory item details', 'item'),
    (gen_random_uuid(), 'item:delete', 'Delete or archive inventory items', 'item'),
    (gen_random_uuid(), 'item:transfer', 'Request inventory item transfers', 'item'),
    (gen_random_uuid(), 'warehouse:create', 'Create new warehouses', 'warehouse'),
    (gen_random_uuid(), 'warehouse:read', 'View warehouse information', 'warehouse'),
    (gen_random_uuid(), 'warehouse:update', 'Update warehouse details', 'warehouse'),
    (gen_random_uuid(), 'warehouse:delete', 'Delete warehouses', 'warehouse'),
    (gen_random_uuid(), 'role:create', 'Create new roles', 'role'),
    (gen_random_uuid(), 'role:read', 'View roles', 'role'),
    (gen_random_uuid(), 'role:update', 'Update role details', 'role'),
    (gen_random_uuid(), 'role:delete', 'Delete roles', 'role'),
    (gen_random_uuid(), 'role:assign', 'Assign roles to users', 'role'),
    (gen_random_uuid(), 'user:invite', 'Invite users to company', 'user'),
    (gen_random_uuid(), 'user:read', 'View user information', 'user'),
    (gen_random_uuid(), 'user:update', 'Update user details', 'user'),
    (gen_random_uuid(), 'user:delete', 'Remove users from company', 'user'),
    (gen_random_uuid(), 'approval:approve', 'Approve transfer requests', 'transfer'),
    (gen_random_uuid(), 'approval:reject', 'Reject transfer requests', 'transfer'),
    (gen_random_uuid(), 'logs:read', 'View audit logs', 'audit'),
    (gen_random_uuid(), 'logs:export', 'Export audit logs', 'audit'),
    (gen_random_uuid(), 'backup:create', 'Create manual backups', 'backup'),
    (gen_random_uuid(), 'backup:restore', 'Restore from backups', 'backup'),
    (gen_random_uuid(), 'rule:create', 'Create access control rules', 'rule'),
    (gen_random_uuid(), 'rule:update', 'Update access control rules', 'rule'),
    (gen_random_uuid(), 'rule:delete', 'Delete access control rules', 'rule'),
    (gen_random_uuid(), 'dac:grant', 'Grant discretionary access', 'dac'),
    (gen_random_uuid(), 'dac:revoke', 'Revoke discretionary access', 'dac')
ON CONFLICT (name) DO NOTHING;
